tmdb:
  api:
    key: ${tmdb.api.key}
    baseurl: https://api.themoviedb.org/3


springdoc:
  swagger-ui:
    base-url: /swagger-ui/index.html
    disable-swagger-default-url: true

    # path: /api
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api/swagger.json
    groups:
      enabled: true
  cache:
    disabled: true

spring:
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 50
      order_inserts: true
      order_updates: true
      batch_versioned_data: true
    show-sql: false
